# Generated by Django 3.0.5 on 2020-06-12 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medical', '0003_medical_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='medical_history',
            name='Email',
            field=models.EmailField(default=True, max_length=50),
        ),
    ]
