# Generated by Django 3.0.5 on 2020-06-15 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_account_info'),
        ('Medical', '0004_medical_history_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medical_history',
            name='Email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.SignUp', unique=True),
        ),
    ]
