# Generated by Django 2.2.12 on 2020-06-12 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_auto_20200612_1944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='email',
            new_name='user',
        ),
    ]
