# Generated by Django 2.2.12 on 2020-06-12 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_id', models.IntegerField()),
                ('policy_no', models.CharField(max_length=200)),
                ('insurance_type', models.CharField(max_length=200)),
                ('carrier_type', models.CharField(max_length=200)),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('insurance_carrycode', models.IntegerField()),
                ('insurance_doc', models.FileField(upload_to='insurance_doc')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.SignUp')),
            ],
        ),
    ]
