# Generated by Django 3.0.5 on 2020-05-13 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ambulance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amulance_no', models.CharField(max_length=200)),
                ('driver_name', models.CharField(max_length=200)),
                ('mobile_no', models.IntegerField()),
                ('license', models.CharField(max_length=200)),
                ('experience', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Ambulance',
                'verbose_name_plural': 'Ambulances',
            },
        ),
        migrations.CreateModel(
            name='Genetic_disorder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('symptons', models.CharField(max_length=200)),
                ('symptons_type', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Genetic_disorder',
                'verbose_name_plural': 'Genetic_disorders',
            },
        ),
        migrations.CreateModel(
            name='Medical_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField()),
                ('height', models.IntegerField()),
                ('blood_pressure', models.IntegerField()),
                ('disease_name', models.CharField(max_length=200)),
                ('past_treatment', models.CharField(max_length=200)),
                ('past_injuries', models.CharField(max_length=200)),
                ('past_surgery', models.CharField(max_length=200)),
                ('customer_id', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Medical_history',
                'verbose_name_plural': 'Medicalhistorys',
            },
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=200)),
                ('hospital_id', models.IntegerField()),
                ('ambulance_id', models.IntegerField()),
                ('ambulance_no', models.IntegerField()),
                ('hospital_location', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'Support',
                'verbose_name_plural': 'Supports',
            },
        ),
    ]
