# Generated by Django 3.0.5 on 2020-05-13 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_detail', models.CharField(max_length=200)),
                ('insurance_id', models.IntegerField()),
                ('company_name', models.CharField(max_length=200)),
                ('insurance_type', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Insurance',
                'verbose_name_plural': 'Insurances',
            },
        ),
    ]
