# Generated by Django 3.0.6 on 2020-05-24 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_personal_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_info',
            name='DOB',
            field=models.CharField(max_length=50),
        ),
    ]
