# Generated by Django 3.0.6 on 2020-05-25 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_auto_20200524_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bike_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bike_Model_Name', models.CharField(max_length=50)),
                ('Last_Name', models.CharField(max_length=50)),
                ('Bike_No', models.CharField(max_length=50)),
                ('Bike_Reg_No', models.CharField(max_length=50)),
                ('Licence_No', models.CharField(max_length=50)),
                ('Licence', models.FileField(upload_to='Licence')),
                ('Email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.SignUp')),
            ],
        ),
    ]
