# Generated by Django 3.0.6 on 2020-05-25 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_bike_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bike_info',
            name='Last_Name',
        ),
    ]
