# Generated by Django 3.0.5 on 2020-06-13 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_auto_20200613_1750'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emergency_Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(max_length=50)),
                ('Relationship', models.CharField(max_length=50)),
                ('Number', models.CharField(max_length=10)),
                ('Email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.SignUp', unique=True)),
            ],
        ),
    ]
